#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d ▫ ▫ ▫ ▫ ▫ ▫ ▫

bspc config border_width                1
bspc config window_gap                  1
bspc config top_padding                 32
bspc config bottom_padding              26

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

bspc config normal_border_color         "#252326"
bspc config focused_border_color        "#783e57"
bspc config presel_feedback_color       "#615772"

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Font-manager state=floating center=true
bspc rule -a Ristretto state=floating center=true

#killall nitrogen --restore
#~/.fehbg &
xwallpaper --zoom Wallpapers/elvis-bekmanis-g9qwoPiS0nY-unsplash.jpg &
#polybar -c $HOME/.config/polybar/config.ini
$HOME/.config/polybar/launch.sh
mpd &
exec killall xmobar &

